### ISSUE TITLE
Add a .github

### ISSUE THREAD

**Issue by X-Legendary** [wotanut/status#6]
You should add a `.github` folder with configurations for opening PRs and issues. Would also help if you added a `CONTRIBUTING.md`, just to keep things organized.

**Comment by wotanut** [comment]
Sure I'll write one when I get a chance.

**Comment by wotanut** [comment]
Added with commit [75fa21b](https://github.com/wotanut/status/commit/75fa21b5c7306d6a2300439af84976c68a3de919)

**Comment by X-Legendary** [comment]
Thanks!
