### ISSUE TITLE
Detected other bots to be offline for <1s

### ISSUE THREAD

**Issue by X-Legendary** [wotanut/status#7]
I have my bot, which I added for tracking in Status Checker, and when I went down for less then a second, Status Checker sent the offline message three times.

**Comment by wotanut** [comment]
It shouldn't have sent more than once in 10 seconds, it automatically rate limits itself
```python
if before.id in updated:
    return
    
  updated.append(before.id)
  ```
  this code checks to see if the bot went down within 10 seconds of the bot going down again, perhaps you have the same bot in the database multiple times (bot id and guild id would be useful so I can check for you)
  
  As for the less then a second I'll put in a block of code that waits around 10 seconds and checks to see if the bot is offline

**Comment by X-Legendary** [comment]
I removed my bot from the database, and added him again. The issue is still present though. I hardly think it's an issue with the bot, rather with the API and caching.

**Comment by wotanut** [comment]
perhaps, I'll look into it

also..... `him`?????????????

**Comment by X-Legendary** [comment]
Let's pretend that never existed 😳
And thanks, I'll open a PR if I happen to find a fix for it.

**Comment by wotanut** [comment]
This should've been fixed as of commit [922daf2](https://github.com/wotanut/status/commit/922daf2308adbeab731d790380f1343fdddfa06f), i'll let you know when it's all pulled to prod

**Comment by wotanut** [comment]
UPDATE: It's been pulled to prod, lmk if it's fixed the issue.

**Comment by X-Legendary** [comment]
@wotanut The issue has been fixed when I removed all the tracking bots in my guild and added them back. The issue still comes back after some time. I'll let you know if I find a possible solution to the problem.

**Comment by X-Legendary** [comment]
@wotanut I have tested this on my own fork of the bot aswell as the production build, and as far as I can see, the issue has been solved.
